name: Wiki CI

on:
  push:
    branches:
      - main

permissions:
  contents: write
jobs:
  wiki:
    if: ${{ github.repository_owner == 'kaivian' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout base code
        uses: actions/checkout@v3
        with:
          path: base-code
      - name: Checkout wiki code
        uses: actions/checkout@v3
        with:
          repository: ${{github.repository}}.wiki
          path: wiki
      - name: Push to wiki
        run: |
          cd wiki
          rm *.md
          cp ../base-code/wiki/* ./
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD || (git commit -m "Add changes" && git push)